import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ResponsiveNav from '@/components/Home/Navbar/ResponsiveNav';
import Footer from '@/components/Home/Footer/Footer';

const font = Inter({
   weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
   subsets: ['latin'],
});

export const metadata: Metadata = {
   title: 'Portfolio',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className="scroll-smooth">
         <body className={`${font.className} antialiased bg-[#0d0d1f]`}>
            <ResponsiveNav />
            {children}
            <Footer />
         </body>
      </html>
   );
}
